config/routes.rb
Rails.application.routes.draw do

    root to: 'static_pages#index'
    get 'sobre', to: 'static_pages#sobre'
    get 'contato', to: 'static_pages#contato'

    resources :contacts
    resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

    validates :name, presence: true, length: {maximum: 50}
    validates :password, length: {minimum: 6}
    validates :email, presence: true, length: {maximum: 255},
                                      format: {with: VALID_EMAIL_REGEX},
                                      uniqueness: {case_sensitive: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

    def index
        @nome = 'Wendel Lopes dos Santos'
    end

    def sobre

    end

    def contato

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = 'Usuário cadastrado com sucesso'
            redirect_to root_url
        else
            render 'new'
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>

    <div class="">
        <div class="alert alert-danger" role="alert" style='display: inline-block'>
            Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'erros') %>

            <ul>
                <% object.errors.full_messages.each do |msg|  %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <small>
        <%= link_to 'Contat List. Todos os direitos reservados', root_path %>
    </small>
    <nav>
        <ul>
            <li>
                <%= link_to 'Sobre', sobre_path %>
            </li>
            <li>
                <%= link_to 'Contato', contato_path %>
            </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top">

  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#expanded-menu" aria-expanded=" false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Contact List', root_url, class: 'navbar-brand' %>
    </div>

  <!-- Conteudo exibido em telas maiores e que serao escondidos em telas menores -->
  <div class="collapse navbar-collapse" id="expanded-menu">
    <ul class="nav navbar-nav">

        <li class="active">
          <%= link_to 'Nova Conta', new_user_path %>
        </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">

        <li>
          <%= link_to 'Entrar', '#' %>
      </li>


    </ul>

  </div>

  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contact List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <div class="container">
        <% flash.each do |message_type, message| %>
       <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
         <button type="button" class="close" data-dismiss="alert" aria-label="Close">
           <span aria-hidden="true">&times;</span>
         </button>
         <%= message %>
       <% end %>
     <% end %>


        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>

  </body>
</html>

app/views/static_pages/contato.html.erb
<h1>Contato</h1>

<p>
    Entre em contato com <a href="#">@eufaleiepronto</a> para saber mais!!!
</p>

app/views/static_pages/index.html.erb
<div class='jumbotron'>
    <h1>Contact List</h1>
    <p>Gegencie seus contatos aqui</p>
    <p>
        <%= link_to 'Crie sua conta', new_user_path, class: 'btn btn-primary btn-lg' %>
    </p>
</div>

app/views/static_pages/sobre.html.erb
<h1>Sobre</h1>
<p>
    Criando com intuito de de conduzir a respeito de quem somos.
</p>

app/views/users/new.html.erb
<div class="row">
    <div class="col-xs-12">
        <h1>Cadastre-se</h1>
    </div>

    <div class="col-md-6 col-md-offset-3 col-xm-12">
        <%= form_for @user do |f| %>
        <%= render 'layouts/error_messages', object: f.object %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control'  %>
            </div>
            <div class="form-group">
                  <%= f.label :password %>
                  <%= f.password_field :password, class: 'form-control' %>
            </div>
            <div class="form-group">
                  <%= f.label :password_confirmation %>
                  <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>

            <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>